plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

title: Toki Pona - Bulgarian dictionary
description: Toki Pona - Bulgarian dictionary
repository: salif/tok_bul_dictionary

author:
  name: Salif Mehmed
  url: https://salif.eu

defaults:
  - scope:
      path: "*.md"
    values:
      lang: "bg"
  - scope:
      path: "*.en.md"
    values:
      lang: "en"
